desc: 展期订单
spring:
  datasource:
    url: jdbc:mysql://192.168.2.181:3306/zqdb?useUnicode=true&amp;characterEncoding=UTF-8
    username: bmdb
    password: ENC(hZ1oe0u6d7jAbgH/KEbVH8yQiVs6Iee+)

jasypt:
  encryptor:
    password: qwer1234tyu

jedis:
  host: 127.0.0.1
  port: 6379
  maxTotal: 100
  maxIdle: 50
  maxWaitMillis: 1000

value:
  loader:
    jsonfile:
      fileBase: D:\work\code\new_orm\config

server:
  port: 11090